version: 2  # use CircleCI 2.0 instead of CircleCI Classic
# https://circleci.com/docs/2.0/language-elixir/
aliases:
  dockerBuildEnv: &dockerBuildEnv
    docker:
      - image: circleci/buildpack-deps:xenial
    environment:
      DOCKERHUB_REPO: aeternity/aeternity

# executors:
#   buildpack:
#     docker:
#       - image: circleci/buildpack-deps:xenial
#     environment:
#       DOCKERHUB_REPO: aeternity/aeternity

references:
  install_libsodium: &install_libsodium
    run:
      name: Install libsodium
      environment:
        LIBSODIUM_VERSION: "1.0.16"
      # source: https://github.com/aeternity/docker-builder/blob/master/Dockerfile#L23
      command: |
        LIBSODIUM_DOWNLOAD_URL="https://github.com/jedisct1/libsodium/releases/download/${LIBSODIUM_VERSION}/libsodium-${LIBSODIUM_VERSION}.tar.gz" \
          && curl -fsSL -o libsodium-src.tar.gz "$LIBSODIUM_DOWNLOAD_URL" \
          && mkdir libsodium-src \
          && tar -zxf libsodium-src.tar.gz -C libsodium-src --strip-components=1 \
          && cd libsodium-src \
          && ./configure && make -j$(nproc) && sudo make install && sudo ldconfig \
          && cd ..
  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true
      version: "17.09.0-ce"
commands:
  docker_build_branch:
    steps:
      - run:
          name: Build branch docker image
          command: |
            docker build -t ${DOCKERHUB_REPO:?}:${CIRCLE_BRANCH/\//_} .
      - run:
          name: Start branch docker image
          command: |
            docker run --name ae_${CIRCLE_SHA1:?} ${DOCKERHUB_REPO:?}:${CIRCLE_BRANCH/\//_} bin/aeternity console -noinput -network_id ae_test
          background: true
      - run:
          name: Health check
          command: |
            sleep 60 # give it some so that docker health checks kicks in
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' ae_${CIRCLE_SHA1:?})
            echo $STATUS
            [ $STATUS == 'healthy' ]

jobs:  # basic units of work in a run
  docker_smoke_tests:
    # executor: buildpack
    <<: *dockerBuildEnv
    steps:
      - checkout
      - *setup_remote_docker
      - docker_build_branch  
  build:  # runs not using Workflows must have a `build` job as entry point
    parallelism: 1  # run only one instance of this job in parallel
    docker:  # run the steps with Docker
      - image: circleci/elixir:otp-21  # ...with this image as the primary container; this is where all `steps` will run
        environment:  # environment variables for primary container
          MIX_ENV: test

    working_directory: ~/app  # directory where steps will run

    steps:  # commands that comprise the `build` job
      - checkout  # check out source code to working directory
      - *install_libsodium
      # - run: sudo apt-get update
      # - run: sudo apt-get install libsodium-dev

      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - restore_cache:  # restores saved mix cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: make clean deps compile  # get updated dependencies & compile them
      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:  # make another, less specific cache
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:  # you should really save one more cache (just in case)
          key: v1-mix-cache
          paths: "deps"
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache: # and one more build cache for good measure
          key: v1-build-cache
          paths: "_build"

      - run: mix test  # run all tests in project

      - store_test_results:  # upload junit test results for display in Test Summary
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/test/lib/ae_socket_connector # Replace with the name of your :app
